// src/constants/boot-config.ts
export const BOOT_STEPS = [
  "BOOTING_SYSTEM_CORE",
  "BYPASSING_LOCAL_ENCRYPTION",
  "SYNCING_CLOUD_DATA_NODES",
  "EXECUTING_CREATIVE_SUITE",
  "BIOMETRIC_HANDSHAKE_COMPLETE",
  "OVERRIDE_SUCCESSFUL",
];
