// src/constants/boot-config.ts
export const INITIAL_LOGS = [
  "[SYS] KERNEL_CORE_V1.1.0_LATEST",
  "[NET] SECURE_SOCKET_LAYER: ESTABLISHED",
  "[MEM] HEAP_INIT: 0x00FF82B14 - SUCCESS",
  "[DRV] RENDER_PIPELINE: VULKAN_API_ENABLED",
  "[SEC] ROOT_UID: 0 - ACCESS_GRANTED",
  "[WAR] DB_LATENCY_DETECTION: 12ms",
  "[LOG] NEURAL_LINK: STABLE_CONNECTION",
];

export const BOOT_STEPS = [
  "BOOTING_SYSTEM_CORE",
  "BYPASSING_LOCAL_ENCRYPTION",
  "SYNCING_CLOUD_DATA_NODES",
  "EXECUTING_CREATIVE_SUITE",
  "BIOMETRIC_HANDSHAKE_COMPLETE",
  "OVERRIDE_SUCCESSFUL",
];
